version: '3.3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}"
    container_name: elasticsearch_apm
    volumes:
      - ./elasticsearch/logs/:/usr/share/logs/
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      #      9200作为Http协议，主要用于外部通讯
      #      9300作为Tcp协议，jar之间就是通过tcp协议通讯
      - "9200:9200"
      - "9300:9300"
    environment:
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - apm
#    environment:
#      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  oap:
    image: apache/skywalking-oap-server:${TAG}
    container_name: oap
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
#    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
    networks:
      - apm
  ui:
    image: apache/skywalking-ui:${SKYWALKING_TAG}
    container_name: skywalking_ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: oap:12800
    networks:
      - apm
networks:
  apm:
    driver: bridge