version: "3.3"
services:
  influxdb:
    image: "influxdb:1.7.10"
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      INFLUXDB_DATA_ENGINE: "tsm1"
      INFLUXDB_REPORTING_DISABLED: "false"
    volumes:
      # 挂载数据
      - ./inluxdb/data:/var/lib/influxdb
  grafana:
    image: grafana/grafana:master-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource"
    links:
      - influxdb
    volumes:
      # 挂载数据
      - ./grafana/data:/var/lib/grafana