version: "3.3"
services:
  influxdb:
    image: "influxdb:1.7.10"
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      INFLUXDB_DATA_ENGINE: "tsm1"
      INFLUXDB_REPORTING_DISABLED: "false"
    volumes:
      # 挂载数据
      - ./data:/var/lib/influxdb
