version: '3'

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}"
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/logs/:/usr/share/logs/
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
#      9200作为Http协议，主要用于外部通讯
#      9300作为Tcp协议，jar之间就是通过tcp协议通讯
      - "9200:9200"
      - "9300:9300"
    environment:
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: "docker.elastic.co/logstash/logstash:${ELK_VERSION}"
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - elk

#官网配置很详细参考以下
#https://www.elastic.co/guide/en/kibana/current/docker.html
#https://www.elastic.co/guide/en/kibana/7.4/settings.html
  kibana:
    image: "docker.elastic.co/kibana/kibana:${ELK_VERSION}"
    container_name: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge