version: '3'

services:
  mysql57:
    container_name: mysql57
    image: "cytopia/mysql-5.7:latest"
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    #        MYSQL_USER: 'user'
    #        MYSQL_PASS: '123456'
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
    ports:
      - "3309:3306"