version: '3'

services:
  solr:
    container_name: solr
    image: solr:5
    ports:
      - "8983:8983"
    volumes:
      - ./data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
  zoo1:
    image: zookeeper:latest
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
#      ZOO_SERVERS: server.1=zoo1:2888:3888
#    networks:
#      - solr
