version: '3.3'

services:
  zookeeper1:
    container_name: zookeeper1
    image: zookeeper:latest
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
#      ZOO_SERVERS: server.1=zookeeper1:2888:3888
      TZ: Asia/Shanghai
    volumes:
      - ./zoo1/data:/data
      - ./zoo1/datalog:/datalog

  kafka1:
    container_name: kafka1
    image: confluentinc/cp-kafka:5.3.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_BROKER_ID: 1
      TZ: Asia/Shanghai
    volumes:
      - ./kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper1

  kafka2:
    container_name: kafka2
    image: confluentinc/cp-kafka:5.3.1
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      #      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_BROKER_ID: 2
      TZ: Asia/Shanghai
    volumes:
      - ./kafka2/data:/var/lib/kafka/data
    depends_on:
      - zookeeper1

  kafka3:
    container_name: kafka3
    image: confluentinc/cp-kafka:5.3.1
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      #      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_BROKER_ID: 3
      TZ: Asia/Shanghai
    volumes:
      - ./kafka3/data:/var/lib/kafka/data
    depends_on:
      - zookeeper1

  kafka-manager:
    container_name: kafka-manager1
    image: sheepkiller/kafka-manager
    ports:
      - "8088:9000"
    environment:
      ZK_HOSTS: "zookeeper1:2181"
      TZ: Asia/Shanghai